// <auto-generated />
namespace English.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateText));
        
        string IMigrationMetadata.Id
        {
            get { return "201904230457266_updateText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
